apply plugin: 'com.android.application'

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.krishna.nagabhushansn95.locationsaver"
        minSdkVersion 24
        targetSdk 34
        versionCode 10
        versionName "1.2.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.krishna.nagabhushansn95.locationsaver'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
}
